spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:posgresql://
    password: 'senha'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        hibernate:
          ddl-auto: uptade
        show-sql: 'true'
server:
  port: ${port:8080}
